yaaie/grails-app/controllers/yaaie/ErrorController.groovy
package yaaie

class ErrorController {

    def _500() { render(view: "500") }
}

yaaie/grails-app/controllers/yaaie/HomeController.groovy
package yaaie

class HomeController {

    def index() { }

    def about() { }
}

yaaie/grails-app/controllers/yaaie/SourceCodeController.groovy
package yaaie

class SourceCodeController {

    def index() { }

    def requirements() { }

    def checkout() { }

    def build() { }
}

yaaie/grails-app/controllers/yaaie/ya8puzzle/EightPuzzleController.groovy
package yaaie.ya8puzzle

import yaaie.ya8puzzle.bestfirstsearch.*
import grails.validation.Validateable
import yaaie.ya8puzzle.heuristics.HeuristicType
import yaaie.ya8puzzle.examples.EightPuzzleExamples
import yaaie.ya8puzzle.examples.EightPuzzleExamplesSelector

class EightPuzzleController {

    def eightPuzzleService

    def index() {
        EightPuzzleCommand command = new EightPuzzleCommand()
        [command: command]
    }

    def program() { }

    def conclusions() { }

    def references() { }

    def solve(EightPuzzleCommand command) {
        command.puzzle = EightPuzzleExamplesSelector.selectExample(command.example)
        command.validate()
        if (command.hasErrors()) {
            render(view: "index", model: [command: command])
            return
        }

        Solution solution
        try {
            solution = eightPuzzleService.solve(command.heuristicType, command.goal, command.puzzle, command.limit, command.downhill)
            if (!solution)
                render(view: "fail")

            render(view: "solution", model: [solution: solution])
        } catch (AStarException ae) {
            Solution failure = new Solution(node: ae.currentNode, goal: ae.goalArray, nodesCreated: ae.nodesCreated, nodesExpanded: ae.nodesExpanded, limit: ae.limit)
            render(view: "fail", model: [currentNode: failure])
        }
    }

    def selectPuzzle() {
        EightPuzzleExamples example = params.example
        int [] puzzle = EightPuzzleExamplesSelector.selectExample(example)
        EightPuzzleCommand command = new EightPuzzleCommand(puzzle: puzzle)
        render(template: "exampleBoard", model: [command: command])
    }
}

@Validateable
class EightPuzzleCommand {
    int [] goal = [1, 2, 3, 8, 0, 4, 7, 6, 5]
    EightPuzzleExamples example = EightPuzzleExamples._1
    int [] puzzle = [2, 8, 3, 1, 6, 4, 7, 0, 5]
    int limit = 100
    boolean downhill = false
    HeuristicType heuristicType = HeuristicType.MISPLACED_TILES

    def static constraints = {
        goal size: 9..9
        puzzle size: 9..9
        limit range: 100..1500
        heuristicType inList: [HeuristicType.MISPLACED_TILES]
    }
}

yaaie/grails-app/views/common/_menu.gsp
<div id="status" role="complementary" class="menu">
    <div class="nav">
        <h1><g:link name="home-index" controller="home" class="home"><strong>Y.A.A.I.E.</strong></g:link></h1>
        <ul>
            <li><g:link name="home-about" controller="home" action="about">Sobre</g:link></li>
        </ul>
    </div>
    <div class="nav">
        <h2><g:link name="sourceCode-index" controller="sourceCode"><strong>Código Fonte</strong></g:link></h2>
        <ul>
            <li ><g:link name="sourceCode-requirements" controller="sourceCode" action="requirements">Requerimentos</g:link></li>
            <li><g:link name="sourceCode-checkout" controller="sourceCode" action="checkout">Checkout / Download</g:link></li>
            <li><g:link name="sourceCode-build" controller="sourceCode" action="build">Compilação e Execução</g:link></li>
        </ul>
    </div>
    <div class="nav">
        <h2>Aplicações</h2>
        <g:link name="eightPuzzle-index" controller="eightPuzzle">8-Puzzle</g:link>
        <ul>
            <li><g:link name="eightPuzzle-program" controller="eightPuzzle" action="program">Programa</g:link></li>
            <li><g:link name="eightPuzzle-conclusions" controller="eightPuzzle" action="conclusions">Conclusões</g:link></li>
            <li><g:link name="eightPuzzle-solve" controller="eightPuzzle" action="solve">Solução</g:link></li>
            <li><g:link name="eightPuzzle-references" controller="eightPuzzle" action="references">Referências</g:link></li>
        </ul>
    </div>
</div>

<g:javascript>
    $('a[name="${params.controller}-${params.action}"]').addClass('nav a hover');
</g:javascript>

yaaie/grails-app/views/common/_spinner.gsp
<div id="spinner" style="position: absolute;
left: 0;
top: 0;
bottom: 0;
right: 0;
/* use any background color you like; rgba would be nice, but older IE will ignore it*/
background: #000;
opacity: 0.8;
filter: alpha(opacity=80);
display: none;">
    <img id="img-spinner" src="${createLinkTo(dir: "images", file: "ajax-loader.gif")}" alt="Loading" style="width: 50px;
    height: 57px;
    position: absolute;
    top: 50%;
    left: 50%;
    /* the image is 50x57, so we use negative margins of 1/2 that size to center it*/
    margin: -28px 0 0 -25px;"/>
    <g:message code="spinner.alt" default="Loading&hellip;"/>
</div>

yaaie/grails-app/views/eightPuzzle/_board.gsp
<g:if test="${node}">
    <div id="node-${node.gCost}" class="node" style="display: none;">
    <ya8puzzle:boardInfo node="${node}"/>
</g:if>
<g:else>
    <div class="draw-puzzle" class="node">
</g:else>
<div class="node-puzzle">
    <table border="1">
        <tr>
            <td class="${ (board[0]) == 0 ? 'blank' : 'number'}">${board[0]}</td>
            <td class="${ (board[1]) == 0 ? 'blank' : 'number'}">${board[1]}</td>
            <td class="${ (board[2]) == 0 ? 'blank' : 'number'}">${board[2]}</td>
        </tr>
        <tr>
            <td class="${ (board[3]) == 0 ? 'blank' : 'number'}">${board[3]}</td>
            <td class="${ (board[4]) == 0 ? 'blank' : 'number'}">${board[4]}</td>
            <td class="${ (board[5]) == 0 ? 'blank' : 'number'}">${board[5]}</td>
        </tr>
        <tr>
            <td class="${ (board[6]) == 0 ? 'blank' : 'number'}">${board[6]}</td>
            <td class="${ (board[7]) == 0 ? 'blank' : 'number'}">${board[7]}</td>
            <td class="${ (board[8]) == 0 ? 'blank' : 'number'}">${board[8]}</td>
        </tr>
    </table>
</div>
</div>

yaaie/grails-app/views/eightPuzzle/_boardInfo.gsp
<div class="node-info">
    <g:if test="${node.gCost == 0}">
        <h2>Situação Inicial</h2>
    </g:if>
    <g:if test="${node.direction}">
        <p><strong>Movement:</strong> ${node.direction}</p>
    </g:if>
    <p><strong>g(n):</strong> ${node.gCost}</p>
    <p><strong>h(n):</strong> ${node.hCost}</p>
    <p><strong>f(n):</strong> ${node.pathCost}</p>
    <p><strong>Path Size:</strong> ${node.pathSize}</p>
</div>

yaaie/grails-app/views/eightPuzzle/_exampleBoard.gsp
<ya8puzzle:drawBoard puzzle="${command?.puzzle}"/>
<g:hiddenField name="puzzle" value="${command?.puzzle}"/>

yaaie/grails-app/views/eightPuzzle/_form.gsp
<%@ page import="yaaie.ya8puzzle.examples.EightPuzzleExamples; yaaie.ya8puzzle.heuristics.HeuristicType" %>
<div id="form-container">
    <fieldset>
        <g:hasErrors bean="${command}">
            <div class="errors">
                <g:renderErrors bean="${command}"/>
            </div>
        </g:hasErrors>

        <g:form controller="eightPuzzle" action="solve">

            <label for="puzzle"><strong>Situação Inicial:</strong></label>
            <div id="puzzle">
                <g:select id="example" name="example" from="${EightPuzzleExamples}" optionKey="key" onchange="${remoteFunction(controller: "eightPuzzle", action: "selectPuzzle", params: "\'example=\'+ this.value", update: "example-board")}"/>
                <br>
                <br>
                <div id="example-board">
                    <g:render template="exampleBoard" model="[command: command]"/>
                </div>

            </div>

            <br>

            <label for="goal"><strong>Situação Objetivo:</strong></label>
            <div id="goal">
                <ya8puzzle:drawBoard puzzle="${command?.goal}"/>
                <g:hiddenField name="goal" value="${command?.goal}"/>
            </div>

            <br>

            <label for="heuristicType"><strong>Heurística:</strong></label>
            <g:select name="heuristicType" from="${HeuristicType.MISPLACED_TILES}" optionKey="key" valueMessagePrefix="heuristic.type" disabled="disabled"/>

            <br>

            <label for="downhill"><strong>Estritamente Decrescente (Downhill):</strong></label>
            <g:checkBox name="downhill" value="${command?.downhill}"/>

            <br>

            <label for="limit"><strong>Limite Iterações (número de 100 a 1500):</strong></label>
            <g:textField name="limit" value="${command?.limit}"/>

            <br>

            <g:submitButton name="submit" value="Solucionar!"/>
        </g:form>
    </fieldset>
</div>

<g:javascript>
function updateExampleBoard() {
        var example = $("#exmaple").val();
        alert(example);
        ${remoteFunction(controller: "eightPuzzle", action: "selectPuzzle", params: "'example='+example", update: "example-board")}
    }
</g:javascript>

yaaie/grails-app/views/eightPuzzle/_solutionInfo.gsp
<hr>
<div class="solution-info">
    <h1>Informações Solução</h1>
    <p><strong>Situação Objetivo:</strong></p>
    <ya8puzzle:drawBoard puzzle="${solution.goal}"/>
    <hr>
    <p><strong>Tamanho Caminho Solução:</strong> ${solution.pathSize}</p>
    <p><strong>Nós Criados:</strong> ${solution.nodesCreated}</p>
    <p><strong>Nós Expandidos:</strong> ${solution.nodesExpanded}</p>
    <hr>
    <p><strong>Lista Open:</strong></p>
    <g:each var="node" in="${solution.openList.sort {it.pathCost}}">
        <ya8puzzle:drawSolutionInfoBoard puzzle="${node.puzzleArray}" node="${node}"/>
    </g:each>
    <hr>
    <p><strong>Lista Closed: </strong></p>
    <g:each var="node" in="${solution.closedList.sort {it.pathCost}}">
        <ya8puzzle:drawSolutionInfoBoard puzzle="${node.puzzleArray}" node="${node}"/>
    </g:each>
</div>

yaaie/grails-app/views/eightPuzzle/_solutionInfoBoard.gsp
<div id="solutionNodeInfo-${node.gCost}" class="node">
    <ya8puzzle:boardInfo node="${node}"/>
    <div class="node-puzzle">
        <table border="1">
            <tr>
                <td class="${ (board[0]) == 0 ? 'blank' : 'number'}">${board[0]}</td>
                <td class="${ (board[1]) == 0 ? 'blank' : 'number'}">${board[1]}</td>
                <td class="${ (board[2]) == 0 ? 'blank' : 'number'}">${board[2]}</td>
            </tr>
            <tr>
                <td class="${ (board[3]) == 0 ? 'blank' : 'number'}">${board[3]}</td>
                <td class="${ (board[4]) == 0 ? 'blank' : 'number'}">${board[4]}</td>
                <td class="${ (board[5]) == 0 ? 'blank' : 'number'}">${board[5]}</td>
            </tr>
            <tr>
                <td class="${ (board[6]) == 0 ? 'blank' : 'number'}">${board[6]}</td>
                <td class="${ (board[7]) == 0 ? 'blank' : 'number'}">${board[7]}</td>
                <td class="${ (board[8]) == 0 ? 'blank' : 'number'}">${board[8]}</td>
            </tr>
        </table>
    </div>
</div>

yaaie/grails-app/views/eightPuzzle/conclusions.gsp
<%--
  Created by IntelliJ IDEA.
  User: gabriel
  Date: 11/21/12
  Time: 1:02 PM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Y.A.A.I.E. - 8-Puzzle</title>
</head>
<body>
<div id="page-body" role="main">
</div>
</body>
</html>

yaaie/grails-app/views/eightPuzzle/fail.gsp
<%--
  Created by IntelliJ IDEA.
  User: gabriel
  Date: 11/9/12
  Time: 1:43 AM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Y.A.A.I.E. - 8-Puzzle</title>
</head>
<body>
<div id="page-body" role="main">
    <h1>FAIL!</h1>
</div>
</body>
</html>

yaaie/grails-app/views/eightPuzzle/index.gsp
<%--
  Created by IntelliJ IDEA.
  User: gabriel
  Date: 11/7/12
  Time: 9:45 PM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Y.A.A.I.E. - 8-Puzzle</title>
</head>
<body>
<div id="page-body" role="main">

<ya8puzzle:form commmand="${command}"/>


</div>

</body>
</html>

yaaie/grails-app/views/eightPuzzle/program.gsp
<%--
  Created by IntelliJ IDEA.
  User: gabriel
  Date: 11/20/12
  Time: 8:51 PM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Y.A.A.I.E. - 8-Puzzle</title>
</head>
<body>
<div id="page-body" role="main">
</div>
</body>
</html>

yaaie/grails-app/views/eightPuzzle/references.gsp
<%--
  Created by IntelliJ IDEA.
  User: gabriel
  Date: 11/20/12
  Time: 8:51 PM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Y.A.A.I.E. - 8-Puzzle</title>
</head>
<body>
<div id="page-body" role="main">
</div>
</body>
</html>

yaaie/grails-app/views/eightPuzzle/solution.gsp
<%--
  Created by IntelliJ IDEA.
  User: gabriel
  Date: 11/9/12
  Time: 1:43 AM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Y.A.A.I.E. - 8-Puzzle</title>
</head>
<body>
<div id="page-body" role="main">
    <h1>Solução Encontrada!</h1>

    <div class="solution-nav">
        <input type="button" name="prev" id="prev" value="<<"/>
        <input type="button" name="next" id="next" value=">>"/>
    </div>

    <ya8puzzle:solution solution="${solution}"/>

    <g:javascript>
        var index = 0;
        var pathSize = ${solution.pathSize};
        $('#node-' + index).show();
        $('#prev').attr('disabled', true);

        $('#next').click(function() {
            $('#node-' + index).hide();
            index++;
            $('#node-' + index).show();
            updateSolutionNav();
        });

        $('#prev').click(function() {
            $('#node-' + index).hide();
            index--;
            $('#node-' + index).show();
            updateSolutionNav();
        });

        function updateSolutionNav() {
            if (index == 0)
                $('#prev').attr('disabled', true);
            else
                $('#prev').attr('disabled', false);

            if (index == pathSize) {
                $('#next').attr('disabled', true);
            } else {
                $('#next').attr('disabled', false);
            }
        }
    </g:javascript>
</div>
</body>
</html>

yaaie/grails-app/views/home/about.gsp
<%--
  Created by IntelliJ IDEA.
  User: gabriel
  Date: 11/20/12
  Time: 9:03 PM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Y.A.A.I.E. - Aplicação</title>
</head>
<body>
<div id="page-body" role="main">
</div>
</body>
</html>

yaaie/grails-app/views/home/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Y.A.A.I.E.</title>
</head>
<body>
<div id="page-body" role="main">
    <h2>Yet Another Artificial Inteligence Experiment</h2>

    <div id="controller-list" role="navigation">
        <h2>Aplicação disponível:</h2>
        <ul>
            <li class="controller"><g:link controller="eightPuzzle">8-Puzzle</g:link></li>
        </ul>
    </div>
</div>

</body>
</html>

yaaie/grails-app/views/home/project.gsp
<%--
  Created by IntelliJ IDEA.
  User: gabriel
  Date: 11/20/12
  Time: 9:03 PM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Y.A.A.I.E. - Projeto</title>
</head>
<body>
<div id="page-body" role="main">
</div>
</body>
</html>

yaaie/grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><g:layoutTitle default="Grails"/></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">
    <link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
    <link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'main.css')}" type="text/css">
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'mobile.css')}" type="text/css">
    <r:require module="jquery"/>
    <g:layoutHead/>
    <r:layoutResources />
</head>
<body>
<div id="grailsLogo" role="banner"><g:link url="http://www.grails.org/"><img src="${resource(dir: 'images', file: 'grails_logo.png')}" alt="Powered by Grails"/></g:link></div>
<g:render template="/common/menu"/>
<g:layoutBody/>
<div class="footer" role="contentinfo"><span>Powered By Groovy + Grails + Cloud Foundry</span></div>
<g:render template="/common/spinner"/>
<r:layoutResources />
</body>
</html>

yaaie/grails-app/views/sourceCode/_build-ant.gsp
<div class="build-ant">
    <h4>Apache Ant Build</h4>
    <ul>
        <li>
            <p>Descompacte o arquivo ya8puzzle-1.0.zip no local de sua preferência.</p>
        </li>
        <li>
            <p>Navegue até a raíz do projeto, onde existe o arquivo build.xml</p>
        </li>
        <li>
            <p>Execute o comando ant</p>
            <p><strong>$ ant</strong></p>
        </li>
    </ul>
</div>

yaaie/grails-app/views/sourceCode/_build-jar.gsp
<div class="build-jar">
    <h4>Java JAR</h4>
    <ul>
        <li>
            <p>Navegue até o diretório do arquivo ya8puzzle-1.0.jar</p>
        </li>
        <li>
            <p>Execute o comando java</p>
            <p><strong>java -jar ya8puzzle-1.0.jar</strong></p>
        </li>
    </ul>
</div>

yaaie/grails-app/views/sourceCode/_checkout-download.gsp
<div class="checkout-download">
    <ul>
        <li>
            <p><g:link url="https://bitbucket.org/gabriel24h/yaaie/downloads/ya8puzzle-1.0.jar">Download</g:link> do JAR executável</p>
        </li>
        <li>
            <p><g:link url="https://bitbucket.org/gabriel24h/yaaie/downloads/ya8puzzle-1.0.zip">Download</g:link> do Projeto 8-Puzzle</p>
        </li>
    </ul>
</div>

yaaie/grails-app/views/sourceCode/_checkout-linux.gsp
<div class="checkout-linux">
    <h4>Linux (Ubuntu)</h4>
    <ul>
        <li>
            <p></p>
        </li>
    </ul>
</div>

yaaie/grails-app/views/sourceCode/_checkout-windows.gsp
<div class="checkout-windows">
    <h4>Linux (Ubuntu)</h4>
    <ul>
        <li>
            <p></p>
        </li>
    </ul>
</div>

yaaie/grails-app/views/sourceCode/_compile-linux.gsp
<div class="compile-linux">
    <h4>Linux (Ubuntu)</h4>
    <ul>
        <li>
            <p><g:link url="http://www.oracle.com/technetwork/java/javase/downloads/index.html">Download</g:link> JDK versão 1.6+</p>
        </li>
        <li>
            <p>Download Apache Ant</p>
            <p><strong>$ sudo apt-get install ant</strong></p>
        </li>
        <li>
            <p>Extraia o arquivo do JDK para o local de sua preferência. Exemplo:</p>
            <p><strong>$ mv Downloads/jdk-7u&ltversão&gt-linux-x64.tar.gz development/</strong></p>
            <p><strong>$ cd development</strong></p>
            <p><strong>$ tar zxvf jdk-7u&ltversão&gt-linux-x64.tar.gz</strong></p>
        </li>
        <li>
            <p>Adicionar JDK no Classpath</p>
            <ul>
                <li>
                    <p>Edite o arquivo /etc/profile (~/.bashrc em versões antigas) com o editor de texto de sua preferência.</p>
                    <p><strong>$ sudo nano /etc/profile</strong></p>
                </li>
                <li>
                    <p>Adicione as seguintes linhas no fim do arquivo:</p>
                    <p>JAVA_HOME=/&ltpath aonde foi extraido o JDK&gt/jdk&ltversão&gt</p>
                    <p>PATH=$JAVA_HOME/bin:$PATH export PATH JAVA_HOME</p>
                    <p>CLASSPATH=$JAVA_HOME/lib/tools.jar</p>
                    <p>CLASSPATH=.:$CLASSPATH</p>
                    <p>export PATH JAVA_HOME CLASSPATH</p>
                </li>
                <li>
                    <p>Salve o arquivo e feche o editor de texto.</p>
                </li>
            </ul>
        </li>
        <li>
            <p>Teste a instalação do JDK</p>
            <p><strong>$ java -version</strong></p>
            <p>Se o comando não for encontrado, verifique novamente o classpath e os caminhos de diretório da instalação do JDK.</p>
            <p>Se o erro persistir, pode ser necessário reiniciar o computador.</p>
        </li>
        <li>
            <p>Teste a instalação do Apache Ant</p>
            <p><strong>$ ant -version</strong></p>
            <p>Se o comando não for encontrado, é possível <g:link url="http://ant.apache.org/bindownload.cgi" target="_blank">instalar manualmente</g:link>.</p>
            <p>O processo é análogo à instalação do JDK, com a diferença no nome da variável de ambiente que deverá ser ANT_HOME.</p>
        </li>
    </ul>
</div>

yaaie/grails-app/views/sourceCode/_run-linux.gsp
<div class="run-linux">
    <h4>Linux (Ubuntu)</h4>
    <ul>
        <li>
            <p><g:link url="http://www.oracle.com/technetwork/java/javase/downloads/index.html">Download</g:link> JRE versão 1.6+</p>
        </li>
        <li>
            <p>Extraia o arquivo do JDK para o local de sua preferência. Exemplo:</p>
            <p><strong>$ mv Downloads/jre-7u&ltversão&gt-linux-x64.tar.gz development/</strong></p>
            <p><strong>$ cd development</strong></p>
            <p><strong>$ tar zxvf jre-7u&ltversão&gt-linux-x64.tar.gz</strong></p>
        </li>
        <li>
            <p>Adicionar JRE no Classpath</p>
            <ul>
                <li>
                    <p>Edite o arquivo /etc/profile (~/.bashrc em versões antigas) com o editor de texto de sua preferência.</p>
                    <p><strong>$ sudo nano /etc/profile</strong></p>
                </li>
                <li>
                    <p>Adicione as seguintes linhas no fim do arquivo:</p>
                    <p>JAVA_HOME=/&ltpath aonde foi extraido o JRE&gt/jre&ltversão&gt</p>
                    <p>PATH=$JAVA_HOME/bin:$PATH export PATH JAVA_HOME</p>
                    <p>CLASSPATH=$JAVA_HOME/lib/tools.jar</p>
                    <p>CLASSPATH=.:$CLASSPATH</p>
                    <p>export PATH JAVA_HOME CLASSPATH</p>
                </li>
                <li>
                    <p>Salve o arquivo e feche o editor de texto.</p>
                </li>
            </ul>
        </li>
        <li>
            <p>Teste a instalação do JRE</p>
            <p><strong>$ java -version</strong></p>
            <p>Se o comando não for encontrado, verifique novamente o classpath e os caminhos de diretório da instalação do JRE.</p>
            <p>Se o erro persistir, pode ser necessário reiniciar o computador.</p>
        </li>
    </ul>
</div>

yaaie/grails-app/views/sourceCode/index.gsp
<%--
  Created by IntelliJ IDEA.
  User: gabriel
  Date: 11/20/12
  Time: 9:04 PM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Y.A.A.I.E. - Código Fonte</title>
</head>
<body>
<div id="page-body" role="main">
    <h1>Código Fonte</h1>
    <div id="content">
        <div class="text">
            <p>Esta aplicação foi desenvolvida em <g:link url="http://www.grails.org/" target="_blank">Grails</g:link>, um framework para desenvolvimento de aplicações web utilizando a linguagem dinâmica de programação <g:link url="http://groovy.codehaus.org/" target="_blank">Groovy</g:link>.</p>
        </div>
        <div class="text">
            <p>O único módulo até o momento, <g:link controller="eightPuzzle">8-Puzzle</g:link>, foi desenvolvido apenas em Groovy e compressado em um Java Archive (JAR) executável.</p>
            <p>Isso é possível pois o Groovy é desenvolido para a plataforma Java, sendo possível compilar os scripts Groovy para Java bytecodes e até mesmo mesclar os códigos.</p>
            <p>Para facilitar o processo de compilação, foi utilizada a ferramenta <g:link url="http://ant.apache.org/" target="_blank">Apache Ant</g:link>, um dos <g:link action="requirements">requerimentos</g:link> para compilar o projeto 8-Puzzle em seu computador.</p>
        </div>
        <div class="text">
            <p>Com isso, é possível fazer o <g:link url="https://bitbucket.org/gabriel24h/yaaie/downloads/ya8puzzle-1.0.jar">download</g:link> do JAR e executá-lo em sua máquina tendo apenas o Java Runtime Environment (JRE) instalado.</p>
            <p>Ou facilmente <g:link controller="eightPuzzle" action="solve">acoplá-lo</g:link> numa aplicação web.</p>
        </div>
        <div class="text">
            <p>Nesta seção, vamos abordar detalhes de como utilizar o projeto em seu computador, começando pelos seus <g:link action="requirements">requerimentos</g:link>.</p>
        </div>
    </div>
</div>
</body>
</html>